name: Build and Deploy docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

permissions:
  contents: write

jobs:
    docs:
      name: build and deploy docs
      runs-on: ubuntu-latest

      steps:      
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            submodules: recursive
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: |
            sudo apt-get update -y -qq
            sudo apt-get install -y --force-yes -qq build-essential python3-dev
            python -m pip install --upgrade pip

            # Pin sphinx to an older version until sphinx-multiversion is fixed
            # see
            # https://github.com/sphinx-contrib/multiversion/pull/202
            python -m pip install "sphinx<8.2" sphinx-rtd-theme

            # This should pull in the fixed version of multiversion when its available
            python -m pip install "sphinx-multiversion @ git+https://github.com/sphinx-contrib/multiversion.git"
            
            python -m pip show sphinx sphinx-multiversion
            sphinx-build --version
            sphinx-multiversion --version || true
        - name: build code
          run: |
            mkdir -p build
            cmake -DSINGULARITY_BUILD_PYTHON=ON \
                  -DSINGULARITY_USE_SPINER=ON \
                  -DSINGULARITY_USE_SPINER_WITH_HDF5=OFF \
                  -DSINGULARITY_FORCE_SUBMODULE_MODE=ON \
                  -B build .
            cmake --build build --parallel 4
            sudo cmake --install build
        - name: build docs
          run: |
            cd doc/sphinx
            PYVERSION=$(python -c "from platform import python_version; print('.'.join(python_version().split('.')[:2]))")
            export PYTHONPATH=/usr/local/lib/python${PYVERSION}/site-packages:$PYTHONPATH
            make multiversion
        - name: Deploy
          if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
          uses: peaceiris/actions-gh-pages@v3.7.3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./doc/sphinx/_build/html
            force_orphan: true
