name: Tests Minimal No Kokkos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    tests-minimal:
      name: Run minimal set of tests, to constrain minimal build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: |
            sudo apt-get update -y -qq
            sudo apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages -qq build-essential
        - name: build and run tests
          run: |
            mkdir -p bin
            cd bin
            mkdir -p ${HOME}/install
            cmake -DCMAKE_INSTALL_PREFIX=${HOME}/install \
                  -DSINGULARITY_USE_SPINER=OFF \
                  -DSINGULARITY_USE_SPINER_WITH_HDF5=OFF \
                  -DSINGULARITY_BUILD_TESTS=ON \
                  -DSINGULARITY_FORCE_SUBMODULE_MODE=ON \
                  -DSINGULARITY_USE_KOKKOS=OFF \
                  ..
            make -j4
            make install
            make test
            ctest --output-on-failure --rerun-failed
